---
fixtures:
  repositories:
    auditd:
      branch: 5.X
      repo: git://github.com/simp/pupmod-simp-auditd
    augeasproviders_core:
      branch: 5.X
      repo: git://github.com/simp/augeasproviders_core
    augeasproviders_grub:
      branch: 5.X
      repo: git://github.com/simp/augeasproviders_grub
    augeasproviders_sysctl:
      branch: 5.X
      repo: git://github.com/simp/augeasproviders_sysctl
    compliance_markup:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-compliance_markup
    haveged:
      branch: 5.X
      repo: https://github.com/simp/puppet-haveged
    iptables:
      branch: 5.X
      repo: git://github.com/simp/pupmod-simp-iptables
    krb5:
      branch: 5.X
      repo: https://github.com/simp/pupmod-simp-krb5
    pki:
      branch: 5.X
      repo: git://github.com/simp/pupmod-simp-pki
    selinux:
      branch: 5.X
      repo: git://github.com/simp/pupmod-simp-selinux
    simpcat:
      branch: 5.X
      repo: git://github.com/simp/pupmod-simp-concat
    simplib:
      branch: 5.X
      repo: git://github.com/simp/pupmod-simp-simplib
    stdlib:
      branch: 5.X
      repo: git://github.com/simp/puppetlabs-stdlib
    stunnel:
      branch: 5.X
      repo: git://github.com/simp/pupmod-simp-stunnel
    svckill:
      branch: 5.X
      repo: git://github.com/simp/pupmod-simp-svckill
    sysctl:
      branch: 5.X
      repo: git://github.com/simp/pupmod-simp-sysctl
    tcpwrappers:
      branch: 5.X
      repo: git://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    nfs: "#{source_dir}"
