---
fixtures:
  repositories:
    auditd: "git://github.com/simp/pupmod-simp-auditd"
    augeasproviders_core:
      repo: "git://github.com/simp/augeasproviders_core"
      branch: "simp-master"
    augeasproviders_grub:
      repo: "git://github.com/simp/augeasproviders_grub"
      branch: "simp-master"
    augeasproviders_sysctl:
      repo: "git://github.com/simp/augeasproviders_sysctl"
      branch: "simp-master"
    common: "git://github.com/simp/pupmod-simp-common"
    simp: "git://github.com/simp/pupmod-simp-simp"
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    simpcat: "git://github.com/simp/pupmod-simp-concat"
    functions: "git://github.com/simp/pupmod-simp-functions"
    iptables: "git://github.com/simp/pupmod-simp-iptables"
    pki: "git://github.com/simp/pupmod-simp-pki"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
    stunnel: "git://github.com/simp/pupmod-simp-stunnel"
    svckill: "git://github.com/simp/pupmod-simp-svckill"
    sysctl: "git://github.com/simp/pupmod-simp-sysctl"
    tcpwrappers: "git://github.com/simp/pupmod-simp-tcpwrappers"
    compliance_markup: "https://github.com/trevor-vaughan/pupmod-compliance"
  symlinks:
    nfs: "#{source_dir}"
