---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core:
      repo: https://github.com/simp/augeasproviders_core
      branch: simp-master
    augeasproviders_grub:
      repo: https://github.com/simp/augeasproviders_grub
      branch: simp-master
    augeasproviders_sysctl:
      repo: https://github.com/simp/augeasproviders_sysctl
      branch: simp-master
    autofs: https://github.com/simp/pupmod-simp-autofs
    concat:
      # master is at 4.0.1, but we are bound to < 4.0.0 in our metadata.json
      repo: https://github.com/simp/puppetlabs-concat
      ref: 3.0.0
    haveged:
      repo: https://github.com/simp/puppet-haveged
      branch: simp-master
    iptables: https://github.com/simp/pupmod-simp-iptables
    krb5: https://github.com/simp/pupmod-simp-krb5
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    selinux: https://github.com/simp/pupmod-simp-selinux
    simplib: https://github.com/simp/pupmod-simp-simplib
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    stdlib: https://github.com/simp/puppetlabs-stdlib
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    svckill: https://github.com/simp/pupmod-simp-svckill
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    nfs: "#{source_dir}"
